- name: play level variables
  hosts: local
  connection: local
  vars_file:
  - course.yml
  tasks:
  - name: print the course info
    ansible.builtin.debug:
      msg: "course name is: {{ COURSE }}, duration: {{ DURATION }}, trainer is: {{ TRAINER }}"